2.PyShop-Mosh/products/urls.py
from django.urls import path
from . import views, forms

app_name = 'product'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('index/', views.IndexView.as_view(), name='index'),
    path('list/<int:pk>/', views.ProductDetailView.as_view(), name='detail'),
    path('list/', views.ProductListView.as_view(), name='list'),
    path('create/', views.ProductCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.ProductUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.ProductDeleteView.as_view(), name='delete'),
    path('user_login/', views.user_login, name='user_login'),
    # path('user_logout/', views.user_logout, name='user_logout'),

]

2.PyShop-Mosh/pyshop/urls.py
from django.contrib import admin
from django.urls import path, include
from products import views
from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('products/', include('products.urls'), name='products'),
    path('logout/', views.user_logout, name='logout'),
    path('login/', views.user_login, name='login'),
]

2.PyShop-Mosh/products/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.FloatField()
    stock = models.IntegerField()
    image_url = models.CharField(max_length=2083)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product:detail', kwargs={'pk': self.pk})


class Offer(models.Model):
    code = models.CharField(max_length=10)
    description = models.CharField(max_length=255)
    discount = models.FloatField()


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

2.PyShop-Mosh/products/forms.py
from django import forms
from .models import Product, UserProfileInfo
from django.contrib.auth.models import User



class PostProduct(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

2.PyShop-Mosh/products/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from .forms import UserForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import (TemplateView,
                                  ListView, DetailView,
                                  CreateView, UpdateView,
                                  DeleteView)
from django.urls import reverse_lazy, reverse
from . import forms, models

from .forms import PostProduct


class IndexView(TemplateView):
    template_name = 'index.html'


class ProductListView(ListView):
    context_object_name = 'products'
    models = models.Product

    def get_queryset(self):
        return models.Product.objects.order_by('id')


class ProductDetailView(LoginRequiredMixin, DetailView):
    login_url = '/products/user_login/'
    redirect_field_name = 'products/product_detail_page.html'
    context_object_name = 'product_detail'
    model = models.Product
    template_name = 'products/product_detail_page.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset


class ProductCreateView(LoginRequiredMixin, CreateView):
    login_url = '/products/user_login/'
    fields = ('name', 'price', 'stock', 'image_url')
    model = models.Product


class ProductUpdateView(UpdateView):
    fields = ('name', 'price', 'stock', 'image_url')
    models = models.Product

    def get_queryset(self):
        return models.Product.objects.order_by('id')


class ProductDeleteView( DeleteView):

    model = models.Product
    success_url = reverse_lazy('product:list')


def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

        registered = True

    else:
        user_form = UserForm()

    return render(request, 'registration.html',
                  {'user_form': user_form,
                   'registered': registered})


def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                print("logged it")
                return render(request, 'index.html')
            else:
                return HttpResponse('account not active')
        else:
            print("someone tried to log")
            return render(request, 'products/login.html')
    else:
        return render(request, 'products/login.html')


@login_required
def user_logout(request):
    logout(request)
    print('logged out')
    return render(request, 'index.html')

2.PyShop-Mosh/products/templates/products/form_page.html
{% extends 'base.html' %}
{% block content %}
    <h1>Please add a new Product!</h1>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
{% endblock %}

2.PyShop-Mosh/products/templates/products/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% if user.is_authenticated %}
<h1> thank you for logging in</h1>
{% else %}
<div class="jumbotron">
    <h1>Please Login Below</h1>
    <form action="{% url 'product:user_login' %}" method="POST">
        {% csrf_token %}

        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username" >

        <label for="password">Password:</label>
        <input type="password" name="password" placeholder="Enter Password">

        <input type="submit" value="Login" >
    </form>
</div>
{% endif %}

{% endblock %}

2.PyShop-Mosh/products/templates/products/product_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
   <h1>Delete {{ product.name }}?</h1>

    <form method="post">
       {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'product:detail' pk=product.pk %} ">Cancel</a>

    </form>
{% endblock %}

2.PyShop-Mosh/products/templates/products/product_detail_page.html
{% extends 'base.html' %}

{% block content %}

<div>
        <h1>This is your product</h1><br>
        <h3>Product Type: {{ product_detail.name }}</h3>
        <h3>Product Price: {{ product_detail.price }}</h3>
        <h3>Current Stock: {{ product_detail.stock }}</h3>
        <img class="images" src="{{ product_detail.image_url }}">
        <p></p>
        <a class='btn btn-danger' href="{% url 'product:delete' pk=product_detail.pk %} ">Delete</a>
        <a class='btn btn-warning' href="{% url 'product:update' pk=product_detail.pk %} ">Update</a>
        <a class='btn btn-warning' href="{% url 'product:list' %} ">Cancel</a>
</div>

{% endblock %}

2.PyShop-Mosh/products/templates/products/product_form.html
{% extends 'base.html' %}
{% block content %}

<h1>
    {% if not form.instance.pk %}
    Create a new Product
    {% else %}
    Update Existing Product
    {% endif %}
</h1>
<form method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Submit" >
    <a class='btn btn-warning' href="{% url 'product:list' %} ">Cancel</a>

</form>

{% endblock %}

2.PyShop-Mosh/products/templates/products/product_list.html
{% extends 'base.html' %}
{% block content %}
<h1 style="text-align:center;">Products</h1>
<div class="row" >
    {% for product in products %}
    <div class="col" >
        <div class="card" style="width: 18rem;"  >
            <img src="{{ product.image_url }}" class="card-img-top">
            <div class="card-body" style="text-align:center;" >
                <h5 class="card-title"><a href="{{product.id}}">{{  product.name }}</a></h5>
                <p class="card-text"> ${{ product.price }}</p>
                <a href="#" class="btn btn-primary">Add to cart</a>

            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

2.PyShop-Mosh/templates/base.html
<!doctype html>
{% load staticfiles %}

<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>My Shop</title>
</head>
<body>


<!-- As a heading -->
<nav class="navbar navbar-light bg-light">
    <span class="navbar-brand mb-0 h1"><a href="{% url 'product:index' %}">Start Page</a></span>
    <span class="navbar-brand mb-0 h1"><a href="{% url 'product:list' %}">All Products</a></span>
    <span class="navbar-brand mb-0 h1"><a href="{% url 'product:create' %}">Create Product</a></span>
    <span class="navbar-brand mb-0 h1"><a href="{% url 'product:register' %}">Register</a></span>

    {% if user.is_authenticated %}
        <span class="navbar-brand mb-0 h1"><a href="{% url 'logout' %}">Logout</a></span>
    {% else %}
        <span class="navbar-brand mb-0 h1"><a href="{% url 'product:user_login' %}">Login</a></span>
    {% endif %}

</nav>
<div class="container">
    <div class="jumbotron">
    {% block content %}

    {% endblock %}
    </div>
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

2.PyShop-Mosh/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>This is My Start Page. </h1>
<h3>Here you will find my basic shop project</h3>
<h4>Functions available are:</h4><br>
<ul>
    <li><h5>User Authentication system where you need to be logged in in order to operate</h5></li>
    <li><h5>Create Read Update Delete Functions</h5></li>

</ul>

{% endblock %}

2.PyShop-Mosh/templates/registration.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% if registered %}
    <h1>Thank you for registering</h1>
{%  else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>
    <form method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        <input type="submit" value="Register">

    </form>


{% endif %}

{% endblock %}